name: svg_vg_converter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.1
  vector_graphics: ^1.1.19
  path: ^1.9.1
  path_provider: ^2.1.4
  vector_graphics_compiler: ^1.1.19

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
<<<<<<< HEAD
    - assets/
    - assets/svg/
    - assets/vg/
    - assets/vg/1/
    - assets/vg/1/env-cat/
=======
    - assets/pet/
    - assets/pet/1/env_1/
    - assets/pet/1/env_1/item_decoration/
    - assets/pet/1/resource/food/
    - assets/pet/1/resource/groom/
    - assets/pet/1/resource/toy/
    - assets/pet/2/env_1/
    - assets/pet/2/env_1/item_decoration/
    - assets/pet/2/resource/food/
    - assets/pet/2/resource/groom/
    - assets/pet/2/resource/toy/
    - assets/pet/3/env_1/
    - assets/pet/3/env_1/item_decoration/
    - assets/pet/3/resource/food/
    - assets/pet/3/resource/groom/
    - assets/pet/3/resource/toy/
    - assets/pet/4/env_1/
    - assets/pet/4/env_1/item_decoration/
    - assets/pet/4/resource/food/
    - assets/pet/4/resource/groom/
    - assets/pet/4/resource/toy/
    - assets/pet/5/env_1/
    - assets/pet/5/env_1/item_decoration/
    - assets/pet/5/resource/food/
    - assets/pet/5/resource/groom/
    - assets/pet/5/resource/toy/
    - assets/pet_vg/
    - assets/pet_vg/1/env_1/
    - assets/pet_vg/1/env_1/item_decoration/
    - assets/pet_vg/1/resource/food/
    - assets/pet_vg/1/resource/groom/
    - assets/pet_vg/1/resource/toy/
    - assets/pet_vg/2/env_1/
    - assets/pet_vg/2/env_1/item_decoration/
    - assets/pet_vg/2/resource/food/
    - assets/pet_vg/2/resource/groom/
    - assets/pet_vg/2/resource/toy/
    - assets/pet_vg/3/env_1/
    - assets/pet_vg/3/env_1/item_decoration/
    - assets/pet_vg/3/resource/food/
    - assets/pet_vg/3/resource/groom/
    - assets/pet_vg/3/resource/toy/
    - assets/pet_vg/4/env_1/
    - assets/pet_vg/4/env_1/item_decoration/
    - assets/pet_vg/4/resource/food/
    - assets/pet_vg/4/resource/groom/
    - assets/pet_vg/4/resource/toy/
    - assets/pet_vg/5/env_1/
    - assets/pet_vg/5/env_1/item_decoration/
    - assets/pet_vg/5/resource/food/
    - assets/pet_vg/5/resource/groom/
    - assets/pet_vg/5/resource/toy/
>>>>>>> 87a5111af131a0ad6026fa6944d647fac75fff8c
